version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: pop_pul-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pop_pul
      MYSQL_USER: team_user_dev  # 개발용 계정
      MYSQL_PASSWORD: team_password_dev  # 개발용 계정 비밀번호
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
