version: '3'
services:
  # MySQL 서비스
  pop_pul:
    image: mysql:8.0
    container_name: pop_pul-mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pop_pul  # 데이터베이스 자동 생성 추가
    volumes:
      - mysql_data:/var/lib/mysql

  # Spring Boot 애플리케이션
  spring-boot-app:
    image: codegod77/pop_pul_backend:latest  # Docker Hub에서 최신 버전 사용
    container_name: pop_pul-spring-boot
    restart: always
    environment:
      DATABASE_URL: jdbc:mysql://pop_pul-mysql:3306/pop_pul  # MySQL 컨테이너와 연결
      DB_USERNAME: root
      DB_PASSWORD: root
    ports:
      - "8080:8080"  # Spring Boot 애플리케이션 포트
    depends_on:
      - pop_pul  # MySQL이 먼저 시작되어야 Spring Boot가 실행됨

volumes:
  mysql_data:  # MySQL 데이터를 저장할 볼륨
